[wokwi]
version=1
firmware='merged-flash.bin'
elf='.pio/build/wokwi_simulation/firmware.elf' 

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"