name: Firmware build and release

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build ESP32 project
      run: |
        cd firmware
        platformio run -e heltec_wifi_lora_32_V2

    - name: Update version
      run: |
        NEW_VERSION=$(date +"%d%m%y-%H%M%S")
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Create zip archive
      run: |
        cd firmware/.pio/build/heltec_wifi_lora_32_V2/
        zip firmware.zip bootloader.bin partitions.bin firmware.bin

    - name: Create new release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: Release v${{ env.NEW_VERSION }}
        body: Auto-generated release for firmware version ${{ env.NEW_VERSION }}
        draft: false
        prerelease: false

    - name: Upload firmware.bin to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: firmware/.pio/build/heltec_wifi_lora_32_V2/firmware.bin
        asset_name: firmware_v${{ env.NEW_VERSION }}.bin
        asset_content_type: application/octet-stream

    - name: Upload firmware.zip to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: firmware/.pio/build/heltec_wifi_lora_32_V2/firmware.zip
        asset_name: firmware_v${{ env.NEW_VERSION }}.zip
        asset_content_type: application/zip
